---
- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
  tasks:
    - name: hostname for remote server
      shell: hostname
      register: find_output
    - debug:
      var: find_output

