---
- hosts: minikube
  become: yes
  tasks:
  - name: minikube status 
    shell: minikube status
    register: find_output

  - debug:
      var: find_output
      
  - name: kubeclt get pods 
    shell: kubectl get pods
    register: find_output_pods

  - debug:
      var: find_output_pods
